source 'https://rubygems.org'

gem 'chef'
gem 'berkshelf'

gem 'fluentd'
gem 'fluent-plugin-secure-forward'

group :development do
  gem 'knife-solo'
  gem 'capistrano'
  gem 'capistrano-rbenv', github: "capistrano/rbenv"
  gem 'capistrano-bundler'
end
