# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.forward_agent = true
  config.omnibus.chef_version = :latest

  config.vm.box = "CentOS-6.4-x86_64"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v0.1.0/centos64-x86_64-20131030.box"

  config.vm.network :private_network, ip: "192.168.33.200"

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
  
    vb.customize [
      "modifyvm", :id, 
      "--memory", "512",
      "--cpus", "1",
      "--cpuexecutioncap", "80"
    ]
  end

  config.berkshelf.berksfile_path = "./Berksfile"
  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    chef.roles_path = "roles"

    chef.add_role "client"
  end
end
