# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.forward_agent = true

  config.vm.define :centos do |centos|
    centos.vm.box = "CentOS-6.4-x86_64"
    centos.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v0.1.0/centos64-x86_64-20131030.box"
    centos.vm.network :private_network, ip: "192.168.33.100"

    centos.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.customize [
        "modifyvm", :id,
        "--memory", "1024",
        "--cpus", "2",
        "--cpuexecutioncap", "75"
      ]
    end

    centos.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = [
        "cookbooks",
        "site-cookbooks"
      ]

      chef.roles_path = "roles"
      chef.data_bags_path = "data_bags"

      chef.add_role "centos"
    end

  end
end
